name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
        include:
          - os: windows
            extension: ".exe"

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "^1.23"
      - run: go build -o shig-${{matrix.os}}-${{matrix.arch}}${{matrix.extension}} -ldflags "-X 'cmd.version=${{ github.event.release.tag_name }}'" ./main.go
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}
      - uses: SierraSoftworks/gh-releases@v1.0.8
        with:
          files: "shig-${{matrix.os}}-${{matrix.arch}}${{matrix.extension}}"
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: "true"
